#!/usr/bin/env node

/**
 * setup.js — Netflix Backend Automation Script
 * Project: movieist (dev.farhan / Spring Boot 3 + MongoDB)
 *
 * What this script does:
 *   1. Checks required system dependencies (Java 17, Maven)
 *   2. Removes any existing .git folder and reinitialises the repo
 *   3. Configures git user identity
 *   4. Writes the .env file with MongoDB credentials
 *   5. Runs `mvn clean package` to build the JAR
 *   6. Optionally runs the compiled JAR
 *   7. Scaffolds a richer .gitlab-ci.yml pipeline
 *
 * Usage:
 *   node setup.js [--run] [--ci]
 *
 *   --run   Also launch the Spring Boot JAR after a successful build
 *   --ci    Re-generate the .gitlab-ci.yml with a full pipeline
 */

"use strict";

const { execSync, spawn } = require("child_process");
const fs   = require("fs");
const path = require("path");
const readline = require("readline");

// ─── Colour helpers ──────────────────────────────────────────────────────────
const c = {
  reset : "\x1b[0m",
  bold  : "\x1b[1m",
  green : "\x1b[32m",
  yellow: "\x1b[33m",
  red   : "\x1b[31m",
  cyan  : "\x1b[36m",
};
const log   = (msg) => console.log(`${c.green}✔${c.reset}  ${msg}`);
const warn  = (msg) => console.warn(`${c.yellow}⚠${c.reset}  ${msg}`);
const error = (msg) => { console.error(`${c.red}✖${c.reset}  ${msg}`); process.exit(1); };
const info  = (msg) => console.log(`${c.cyan}ℹ${c.reset}  ${msg}`);
const sep   = ()    => console.log(`${c.bold}${"─".repeat(60)}${c.reset}`);

// ─── CLI flags ────────────────────────────────────────────────────────────────
const args   = process.argv.slice(2);
const RUN_JAR = args.includes("--run");
const GEN_CI  = args.includes("--ci");

// ─── Project constants (from pom.xml) ────────────────────────────────────────
const ARTIFACT_ID = "movieist";
const VERSION     = "0.0.1-SNAPSHOT";
const JAR_NAME    = `${ARTIFACT_ID}-${VERSION}.jar`;
const JAR_PATH    = path.join("target", JAR_NAME);
const ENV_PATH    = path.join("src", "main", "resources", ".env");

// ─── Utility: run a shell command synchronously ───────────────────────────────
function run(cmd, opts = {}) {
  try {
    return execSync(cmd, { stdio: "inherit", ...opts });
  } catch (e) {
    error(`Command failed: ${cmd}\n${e.message}`);
  }
}

// ─── Utility: prompt for input ────────────────────────────────────────────────
function prompt(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) =>
    rl.question(`${c.cyan}?${c.reset}  ${question} `, (ans) => { rl.close(); resolve(ans.trim()); })
  );
}

// ─── Step 1: Check dependencies ───────────────────────────────────────────────
async function checkDependencies() {
  sep();
  info("Checking system dependencies…");

  const checks = [
    { cmd: "java --version",  label: "Java 17+" },
    { cmd: "mvn --version",   label: "Maven"    },
    { cmd: "git --version",   label: "Git"      },
  ];

  for (const { cmd, label } of checks) {
    try {
      const out = execSync(cmd, { stdio: "pipe" }).toString().split("\n")[0];
      log(`${label}: ${out}`);
    } catch {
      error(`${label} is not installed or not on PATH.\nInstall it and re-run this script.`);
    }
  }
}

// ─── Step 2: Re-initialise git repo ──────────────────────────────────────────
async function initGit(username, email, remoteUrl) {
  sep();
  info("Initialising Git repository…");

  if (fs.existsSync(".git")) {
    warn("Existing .git folder found — removing it.");
    fs.rmSync(".git", { recursive: true, force: true });
  }

  run("git init");
  run("git add .");
  run(`git commit -m "Initial commit"`);
  run(`git config user.name "${username}"`);
  run(`git config user.email "${email}"`);

  if (remoteUrl) {
    run(`git remote add origin ${remoteUrl}`);
    run("git branch -M main");
    info("Remote added. Push when ready with: git push -u origin main");
  }

  log("Git repository initialised.");
}

// ─── Step 3: Write .env ──────────────────────────────────────────────────────
async function writeEnv(mongoDatabase, mongoCluster) {
  sep();
  info(`Writing environment file → ${ENV_PATH}`);

  const dir = path.dirname(ENV_PATH);
  fs.mkdirSync(dir, { recursive: true });

  const content = [
    `# Auto-generated by setup.js — ${new Date().toISOString()}`,
    `MONGO_DATABASE=${mongoDatabase}`,
    `MONGO_CLUSTER=${mongoCluster}`,
    "",
  ].join("\n");

  fs.writeFileSync(ENV_PATH, content, "utf8");
  log(".env written successfully.");
}

// ─── Step 4: Maven build ──────────────────────────────────────────────────────
async function mavenBuild() {
  sep();
  info("Running Maven build (mvn clean package)…");
  run("mvn clean package -DskipTests");

  if (fs.existsSync(JAR_PATH)) {
    log(`Build successful → ${JAR_PATH}`);
  } else {
    error(`Expected JAR not found at ${JAR_PATH}. Check Maven output above.`);
  }
}

// ─── Step 5: Run JAR (optional) ───────────────────────────────────────────────
function runJar() {
  sep();
  info(`Launching: java -jar ${JAR_PATH}`);
  const proc = spawn("java", ["-jar", JAR_PATH], { stdio: "inherit" });
  proc.on("close", (code) => {
    code === 0 ? log("Application exited cleanly.") : warn(`Application exited with code ${code}.`);
  });
}

// ─── Step 6: Scaffold .gitlab-ci.yml ─────────────────────────────────────────
function generateCiPipeline() {
  sep();
  info("Generating .gitlab-ci.yml pipeline…");

  const pipeline = `# Auto-generated GitLab CI/CD pipeline for ${ARTIFACT_ID}
# Generated by setup.js on ${new Date().toISOString()}

stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  ARTIFACT: "target/${JAR_NAME}"

cache:
  paths:
    - .m2/repository/

# ── Build ─────────────────────────────────────────────────────────────────────
build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "Compiling the project…"
    - mvn compile $MAVEN_OPTS
  artifacts:
    paths:
      - target/

# ── Test ──────────────────────────────────────────────────────────────────────
test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "Running unit tests…"
    - mvn test $MAVEN_OPTS
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

# ── Package ───────────────────────────────────────────────────────────────────
package:
  stage: package
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "Packaging JAR…"
    - mvn clean package -DskipTests $MAVEN_OPTS
  artifacts:
    paths:
      - $ARTIFACT
    expire_in: 1 week

# ── Docker build & push (optional) ───────────────────────────────────────────
docker-build:
  stage: deploy
  image: docker:24
  services:
    - docker:24-dind
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
  only:
    - main
`;

  fs.writeFileSync(".gitlab-ci.yml", pipeline, "utf8");
  log(".gitlab-ci.yml written successfully.");
}

// ─── Main ─────────────────────────────────────────────────────────────────────
(async () => {
  console.log(`\n${c.bold}${c.cyan}Netflix Backend — Setup Script${c.reset}`);
  console.log(`Project: ${ARTIFACT_ID} v${VERSION}\n`);

  await checkDependencies();

  sep();
  info("Please provide your configuration details:");
  const username      = await prompt("Git username:");
  const email         = await prompt("Git email:");
  const remoteUrl     = await prompt("Remote URL (leave blank to skip):");
  const mongoDatabase = await prompt("MONGO_DATABASE name:");
  const mongoCluster  = await prompt("MONGO_CLUSTER connection string:");

  await initGit(username, email, remoteUrl || null);
  await writeEnv(mongoDatabase, mongoCluster);
  await mavenBuild();

  if (GEN_CI) generateCiPipeline();
  if (RUN_JAR) runJar();

  sep();
  log("Setup complete! 🚀");
  if (!RUN_JAR) {
    info(`To start the app: java -jar ${JAR_PATH}`);
  }
  info("To push to GitLab:  git push -u origin main");
  console.log();
})();
